### ISSUE TITLE
No midi outputs available

### ISSUE THREAD

**Issue by w3cj** [aaronats/jsmidi-atom#1]
Hello there! I stumbled across your project while researching ways to control ableton from node.js

I used the cli to generate a basic project and loaded that up in atom, but I do not see any midi devices listed.

I'm running this on Mac OS Mojave 10.14.6

Is there anything else I need to do for initial setup?

![](https://i.imgur.com/yWIVSGQ.png)

**Comment by w3cj** [comment]
I figured it out! I needed to go into Audio / Midi Setup and set the IAC driver to be "online"

![](https://i.imgur.com/wsXR5XE.png)

**Comment by aaronats** [comment]
Hey @w3cj! Glad you figured it out. I am in midst of a few updates.  Just published last week so I could have some friends test everything out.  Would love to get your input on Ableton as I don't have it.  I am planning on posting everything including examples on Hacker News, Reddit, etc. this week. Happy to answer any questions. Cheers!
